<template>
    <v-card>
        <v-card-title>TimeLine</v-card-title>
        <v-card-text>
            <v-timeline>
                <v-timeline-item></v-timeline-item>
            </v-timeline>
        </v-card-text>
    </v-card>
</template>